---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: ingredient
    run_list:
      - recipe[qa-chef-server-cluster::chef_server_ingredient]
  - name: standalone
    run_list:
      - recipe[qa-chef-server-cluster::standalone]
      - recipe[qa-chef-server-cluster::standalone-upgrade]
      - recipe[qa-chef-server-cluster::run-pedant]
    attributes:
  - name: bootstrap-backend
    run_list:
      - recipe[qa-chef-server-cluster::_bootstrap]
      - recipe[qa-chef-server-cluster::_bootstrap-upgrade]
    attributes:
  - name: frontend
    run_list:
      - recipe[qa-chef-server-cluster::_frontend]
      - recipe[qa-chef-server-cluster::_frontend-upgrade]
    attributes:
