---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: standalone
    run_list:
      - recipe[qa-chef-server-cluster::standalone-provision]
    attributes:

