---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: standalone_server_install
    run_list: standalone_server::install
  - name: standalone_server_upgrade
    run_list: standalone_server::upgrade
  - name: standalone_server_test
    run_list: standalone_server::test
