name             'qa-chef-server-cluster'
maintainer       'Patrick Wright'
maintainer_email 'patrick@getchef.com.com'
license          'all_rights'
description      'Installs/Configures QA clusters'
version          '0.1.0'

depends 'chef-server-cluster'
depends 'oc-artifactory'
depends 'lvm'
